<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<AssemblyName>EquiBorrow.UI</AssemblyName>
	<RootNamespace>EquiBorrow.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\EquiBorrow.Application\EquiBorrow.Application.csproj" />
	<ProjectReference Include="..\EquiBorrow.Infrastructure\EquiBorrow.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Compile Include="..\EquiBorrowing.Console\**\*.cs" />
	<AvaloniaXaml Include="..\EquiBorrowing.Console\**\*.axaml" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Avalonia" Version="11.2.4" />
	<PackageReference Include="Avalonia.Desktop" Version="11.2.4" />
	<PackageReference Include="Avalonia.ReactiveUI" Version="11.2.4" />
	<PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.4" />
	<PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.4" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
	<PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

</Project>
